service: product-service
frameworkVersion: '3'

plugins:
  - serverless-auto-swagger

custom: {
  productTableName: products,
  stockTableName: stocks,
  autoswagger: {
    typefiles: ['./src/types/api-types.d.ts']
  }
}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:us-east-1:949025825036:table/products"
    - Effect: "Allow"
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-east-1:949025825036:table/stocks"
    - Effect: "Allow"
      Action: "sns:*"
      Resource: 
        Ref: SNSTopic

functions:
  getProductList:
    handler: handler.getProducts
    events:
      - httpApi:
          path: /products
          method: get
          responseData: {
            200: {
              description: "Complete list of products",
              bodyType: 'Product'
            },
            500: {
              description: "Error returning data"
            }
          }
  getProductsById:
    handler: handler.getProductId
    events:
      - httpApi:
          path: /products/{productId}
          method: get
          responseData: {
            200: {
              description: "Product id provided was found",
              bodyType: 'Product'
            },
            404: {
              description: "Product Id provided not found"
            }
          }
  createProduct:
    handler: handler.createProduct
    events:
      - httpApi:
          path: /products
          method: post
          responseData: {
            200: {
              description: "Product item created",
              bodyType: 'Product'
            },
            500: {
              description: "Error creating product"
            }
          }
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - catalogItemsQueue
              - Arn
          batchSize: 5
          functionResponseType: ReportBatchItemFailures


resources:
  Resources:
    DynamoProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.productTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
    DynamoStockTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stockTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5 
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
    catalogItemsQueue:
     Type: "AWS::SQS::Queue"
     Properties:
       QueueName: catalogItemsQueue.fifo
       FifoQueue: true
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
       TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: lorena_rojas@epam.com
        Protocol: email
        TopicArn: 
          Ref: SNSTopic
