app: serverless-backend
service: authorization-service

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
